# Generated by Django 3.2.8 on 2021-10-14 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyushType',
            fields=[
                ('Ayush_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('Facilities_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareType',
            fields=[
                ('Healthcare_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MiscellaneousFacilities',
            fields=[
                ('MFacilities_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('Speciality_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HospitalUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HospitalSpecialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('Speciality_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalMFacilies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('MFacilities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.miscellaneousfacilities')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalHealthcare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Healthcare_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.healthcaretype')),
                ('Hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facilities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.facilities')),
                ('Hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalAyushtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ayush_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AyushHospital', to='hospital.ayushtype')),
                ('Hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HospitalAyush', to='hospital.hospital')),
            ],
        ),
    ]
